apiVersion: v1
kind: Pod
metadata:
  name: recorder-testing-pod
  labels:
    app: recorder-testing-pod
spec:
  containers:
    - name: recroder-testing-pod
      image: bsuro10/recorder-testing:latest
  nodeSelector:
    kubernetes.io/hostname: 'kind-worker'
  env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: env-config
